name: a3_s08_master
on:
  workflow_dispatch:
permissions:
  actions: write
jobs:
  activar-otro:
    runs-on: ubuntu-latest
    steps:
      - name: llamado1
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: a2_s08_needs.yml
          token: ${{ secrets.GITHUB_TOKEN }}